---
- name: Ping test
  hosts: all
  tasks:
    - name: a simple ping test
      ping:
    - name: list the files
      command: ls -1 chdir=/home/Raja
      register: lsout
    - debug:
        var: lsout.stdout_lines 
