---
- name: Ping test
  hosts: all
  become: true
  tasks:
    - name: install httpd service
      yum: name=httpd state=latest update_cache=yes
    - name: start the service
      service: name=httpd state=started enabled=yes 
